### ISSUE TITLE
Enhance Signup Page UI by Improving Text Visibility and Overall Design

### ISSUE THREAD

**Issue by INam1995** [AlfiyaSiddique/TastyTrails#48]
![image](https://github.com/user-attachments/assets/3f1575d4-b031-452b-a759-365bbbed186c)
Hey @AlfiyaSiddique, as you can see from the screenshot, the signup page design needs improvement. The first name and second name headings have the same color as the background, which negatively affects the UI. I can enhance the design to make it more attractive and user-friendly. Please assign this issue to me under the gssoc-ext label.

**Comment by AlfiyaSiddique** [comment]
@INam1995 This is not an issue and it is due to the dark mode settings of the respective user browser.
It is also an duplicate issue of https://github.com/AlfiyaSiddique/TastyTrails/issues/9#issuecomment-2388505246

You can go through the conversation and let me know in the issue no. 9 if you can take up this based on the requirements given in issue 9.

**Comment by AlfiyaSiddique** [comment]
This issue is completed

**Comment by AlfiyaSiddique** [comment]
This issue is completed
