### ISSUE TITLE
Enhancing Readme.md file

### ISSUE THREAD

**Issue by neeru24** [AlfiyaSiddique/TastyTrails#59]
I’ve been exploring the project and appreciate the work you’ve done so far. I’d like to propose an update to the README.md file to provide a more comprehensive overview of the website. Here are a few ideas I have in mind:

We can use emojis and more animations and can change the way of wrting to make the readme.md more attractive and appealing 

I believe these updates could enhance user understanding and engagement with the project. If you're open to it, I’d love to contribute.

I’m committed to continually improving the quality of our documentation.

Thank you!

**Comment by AlfiyaSiddique** [comment]
But if you still want to work on it and guarantee that your changes will make a huge difference you can start working on it and submit the PR, I will assign the issue to you.
But please note the PR will only be accepted if the changes are impactful. Otherwise, it will discarded.
So you can decide and let, me know if you are up for this @neeru24  or not.

**Comment by neeru24** [comment]
> But if you still want to work on it and guarantee that your changes will make a huge difference you can start working on it and submit the PR, I will assign the issue to you.
> But please note the PR will only be accepted if the changes are impactful. Otherwise, it will discarded.
> So you can decide and let, me know if you are up for this @neeru24  or not.

Sure, Thanks
I'll work on it and submit a pull request 😊👍
