### ISSUE TITLE
Improve the Sign up page

### ISSUE THREAD

**Issue by TanmayKalra09** [AlfiyaSiddique/TastyTrails#9]
We can make the signup page more attractive by rearranging the fields and changing the font and its color.

pls assign me the issue :)

**Comment by AlfiyaSiddique** [comment]
@TanmayKalra09  can you describe more, what designs or changes are you planning to implement?
In my opinion, the signup form is already well-formatted. However, if you have any design suggestions, please feel free to share them in detail.

**Comment by TanmayKalra09** [comment]
Yeah, Sure. On signup, Field names like First Name, Last Name, Username, and Email have dark font colors, which makes them uneasy to read. I would simply change the font color to white, which makes it easy to read.
Additionally, we can rearrange Fields below each other so that users can see what they have entered at once. Like when I was entering my email, I couldn't see the full email address I entered there.
![image](https://github.com/user-attachments/assets/0f715a33-11b2-4dbf-a687-5e7bb952ec8f)

**Comment by AlfiyaSiddique** [comment]
@TanmayKalra09 

The default website looks like this:
![image](https://github.com/user-attachments/assets/1c822227-c3b9-4fac-98ba-ba6261b83bf4)

You are getting a dark interface may be due to your browser settings.

**Comment by AlfiyaSiddique** [comment]
But yes you can work on detecting the dark browser settings and then change the styles.
Also, the field format that you mentioned is already implemented for mobile view, And in web view, I think it will give a long-form appearance, but still as it is not much work you can try if you want but it will be accepted only if it looks good.
Let me know if you are up for this, I will assign this issue to you.

**Comment by paramveer665** [comment]
This is regular on default theme. Indentation was fixed by Prettier extension in VS Code not intentional

![image](https://github.com/user-attachments/assets/a5f0ec78-14fa-4287-802e-93c75cb6ae08)

This is Signup page on dark theme.

![image](https://github.com/user-attachments/assets/f91278fe-6a28-4d75-b17f-4411ea050170)

This is after my fix on same signup page in dark theme.

Signup page on light theme and dark theme after my font fix and added better tailwind shadow
Dark
![image](https://github.com/user-attachments/assets/b460c825-2cac-4ee6-aa4c-d9bfaa17c8a9)

Light
![image](https://github.com/user-attachments/assets/e8a98e65-78bb-478f-a0ec-46f8879b333f)

Kindly add this under Hacktoberfest

**Comment by AlfiyaSiddique** [comment]
Due to no reponse on below query assigning this issue to @paramveer665 
cc: @TanmayKalra09

**Comment by paramveer665** [comment]
@AlfiyaSiddique Thank you very much for assigning this issue to me. I have already fixed font on each field. I will fix the fields and stack on top of each other asap.
Thanks again

**Comment by paramveer665** [comment]
![image](https://github.com/user-attachments/assets/e67bc173-da08-41fc-9033-c590c723a4b7)

Converted all the fields to be stacked on top of each other as per Initial issue features suggestion.
